@AbapCatalog.viewEnhancementCategory: [#NONE]
@AccessControl.authorizationCheck: #NOT_REQUIRED
@EndUserText.label: 'BOM Item Basic'
@Metadata.ignorePropagatedAnnotations: false
@ObjectModel.usageType: {serviceQuality: #A, sizeCategory: #L, dataClass: #MASTER}
define view entity ZPP_I_BOMItemBasic
  as select from I_BillOfMaterialItemBasic as item

{
  key item.BillOfMaterialCategory,
  key item.BillOfMaterial,
  key item.BillOfMaterialItemNodeNumber,
  key item.BOMItemInternalChangeCount,
      item.BillOfMaterialItemUUID,
      item.InheritedNodeNumberForBOMItem,
      item.InheritedNodeNumberVersionBOM,
      item.ValidityStartDate,
      item.ValidityEndDate,
      item.EngineeringChangeDocument,
      item.ChgToEngineeringChgDocument,
      item.BOMItemRecordCreationDate,
      item.BOMItemCreatedByUser,
      item.BOMItemLastChangeDate,
      item.BOMItemLastChangedByUser,
      item.BillOfMaterialComponent,
      item.BillOfMaterialItemCategory,
      item.BillOfMaterialItemNumber,
      item.BillOfMaterialItemUnit,
      item.BillOfMaterialItemQuantity,
      item.IsSubItem,
      item.BOMItemSorter,
      item.FixedQuantity,
      item.PurchasingGroup,
      item.Currency,
      item.MaterialComponentPrice,
      item.IdentifierBOMItem,
      item.MaterialPriceUnitQty,
      item.ComponentScrapInPercent,
      item.OperationScrapInPercent,
      item.IsNetScrap,
      item.NumberOfVariableSizeItem,
      item.QuantityVariableSizeItem,
      item.FormulaKey,
      item.BOMItemText1,
      item.BOMItemText2,
      item.MaterialGroup,
      item.DocumentType,
      item.DocNumber,
      item.DocumentVersion,
      item.DocumentPart,
      item.ClassNumber,
      item.ClassType,
      item.ResultingItemCategory,
      item.DependencyObjectNumber,
      item.ObjectType,
      item.IsClassificationRelevant,
      item.IsBulkMaterial,
      item.BOMItemIsSparePart,
      item.BOMItemIsSalesRelevant,
      item.IsProductionRelevant,
      item.BOMItemIsPlantMaintRelevant,
      item.BOMItemIsCostingRelevant,
      item.IsEngineeringRelevant,
      item.SpecialProcurementType,
      item.IsBOMRecursiveAllowed,
      item.OperationLeadTimeOffset,
      item.OpsLeadTimeOffsetUnit,
      item.IsMaterialProvision,
      item.BOMIsRecursive,
      item.DocumentIsCreatedByCAD,
      item.DistrKeyCompConsumption,
      item.DeliveryDurationInDays,
      item.Creditor,
      item.CostElement,
      item.Size1,
      item.Size2,
      item.Size3,
      item.UnitOfMeasureForSize1To3,
      item.GoodsReceiptDuration,
      item.PurchasingOrganization,
      item.RequiredComponent,
      item.MultipleSelectionAllowed,
      item.ProdOrderIssueLocation,
      item.MaterialIsCoProduct,
      item.ExplosionType,
      item.FollowUpGroup,
      item.DiscontinuationGroup,
      item.ReinsurContrOrgUnit,
      item.IsConfigurableBOM,
      item.ReferencePoint,
      item.LeadTimeOffset,
      item.IsSoftwareComponent,
      item.ProductionSupplyArea,
      item.IsDeleted,
      item.IsALE,
      item.AlternativeItemGroup,
      item.AlternativeItemPriority,
      item.AlternativeItemStrategy,
      item.UsageProbabilityPercent,
      item._BOMItemCategory,
      item._BOMItemCategoryText,
      item._Currency,
      item._DocumentText,
      item._Product,
      item._ProductText,
      item._UnitOfMeasure
}
